import type { CaseStudy } from './types'

export const trackhrs: CaseStudy = {
  slug: 'trackhrs',
  meta: {
    title: 'TrackHRS: time tracking & activity intelligence',
    description: 'Founder and architect of TrackHRS: a Rust desktop agent and 8 NestJS microservices in an event-driven pipeline built on Kafka, Redis and MongoDB.',
  },
  hero: {
    eyebrow: 'Founder · Product & Architecture',
    title: 'TrackHRS',
    subtitle: 'A distributed time tracking and activity intelligence platform: desktop agent, web apps and event-driven microservices, designed and shipped end to end.',
    role: 'Founder & Lead Architect',
    links: [{ label: 'Visit trackhrs.com', href: 'https://trackhrs.com', icon: 'lucide:external-link' }],
  },
  stats: [
    { value: '12', label: 'Product components', description: 'Desktop agent, web apps and backend services' },
    { value: '8', label: 'NestJS microservices', description: 'Independently deployable domain services' },
    { value: '100×', label: 'Fewer immediate writes', description: 'Batching on the ingest path cuts write amplification' },
  ],
  overview: {
    heading: 'Turning raw desktop activity into decisions people trust',
    paragraphs: [
      'TrackHRS is a full-stack time tracking and activity intelligence platform for distributed teams. It combines a native desktop agent, two web applications and a set of event-driven microservices that capture work activity, classify it, and turn it into analytics HR and operations teams can act on.',
      'The hard part was never the dashboard. It was the path between a keystroke on someone’s laptop and a number a manager is willing to trust. That path has to stay accurate when the network drops, stay fast when traffic spikes, and never double-count an event because two replicas processed it at once.',
      'I designed the architecture around asynchronous pipelines, cache-first reads and multi-replica-safe processing, so each of those failure modes is handled by a specific mechanism rather than by hope.',
    ],
  },
  problems: [
    {
      title: 'Accurate time tracking',
      description: 'Time captured across tasks and projects with reliable aggregation, even when a laptop goes offline mid-session.',
      icon: 'lucide:clock',
    },
    {
      title: 'Activity intelligence',
      description: 'Automated categorisation of activity so operational insight does not depend on people filling in timesheets.',
      icon: 'lucide:chart-line',
    },
    {
      title: 'Operational visibility',
      description: 'Dashboards and reporting that HR, managers and operations teams can act on in near real time.',
      icon: 'lucide:eye',
    },
  ],
  architecture: {
    heading: 'High-level architecture',
    intro: 'Four layers, each scaling on its own terms. Clients never talk to storage directly, and nothing time-sensitive shares a path with anything slow.',
    layers: [
      {
        title: 'Client layer',
        caption: 'What people actually use',
        nodes: [
          { name: 'Desktop agent', tech: 'Tauri 2 · Rust', icon: 'lucide:monitor' },
          { name: 'Admin portal', tech: 'Next.js', icon: 'lucide:layout-dashboard' },
          { name: 'Marketing site', tech: 'Next.js', icon: 'lucide:globe' },
        ],
      },
      {
        title: 'API & service layer',
        caption: 'Domain services behind REST and gRPC boundaries',
        nodes: [
          { name: 'User service', tech: 'NestJS', icon: 'lucide:users' },
          { name: 'Activity service', tech: 'NestJS', icon: 'lucide:activity' },
          { name: 'Activity provider', tech: 'NestJS', icon: 'lucide:chart-bar' },
          { name: 'Projects manager', tech: 'NestJS', icon: 'lucide:folder-kanban' },
          { name: 'Plans & billing', tech: 'NestJS', icon: 'lucide:credit-card' },
          { name: 'Notifications', tech: 'NestJS', icon: 'lucide:bell' },
          { name: 'Storage producer', tech: 'NestJS', icon: 'lucide:hard-drive' },
          { name: 'Classifier API', tech: 'Python · FastAPI', icon: 'lucide:brain' },
          { name: 'Auto-update server', tech: 'Express', icon: 'lucide:download' },
        ],
      },
      {
        title: 'Event & queue layer',
        caption: 'Where slow work is decoupled from fast work',
        nodes: [
          { name: 'Kafka cluster', tech: 'Ingestion & domain events', icon: 'lucide:git-branch' },
          { name: 'Redis cluster', tech: 'Cache · dedup · locks', icon: 'lucide:zap' },
          { name: 'BullMQ workers', tech: 'Background jobs', icon: 'lucide:list-checks' },
          { name: 'RabbitMQ bus', tech: 'Targeted fan-out', icon: 'lucide:split' },
        ],
      },
      {
        title: 'Data & object storage',
        caption: 'Durable state',
        nodes: [
          { name: 'MongoDB replica set', tech: 'Domain persistence', icon: 'lucide:database' },
          { name: 'S3-compatible storage', tech: 'Screenshots & artefacts', icon: 'lucide:hard-drive' },
          { name: 'Local SQLite', tech: 'Desktop offline buffer', icon: 'lucide:save' },
        ],
      },
    ],
  },
  serviceComponents: [
    { name: 'tracking/', role: 'Tauri desktop agent for activity capture and local runtime', tech: ['Tauri 2', 'Rust', 'React'], icon: 'lucide:monitor' },
    { name: 'activity/', role: 'Activity ingestion and classification orchestration', tech: ['NestJS', 'Kafka'], icon: 'lucide:activity' },
    { name: 'activity-provider/', role: 'Read and statistics APIs for dashboards and reporting', tech: ['NestJS', 'Redis'], icon: 'lucide:chart-bar' },
    { name: 'activity_classifier/', role: 'ML and rule-based classification service', tech: ['Python', 'FastAPI'], icon: 'lucide:brain' },
    { name: 'user-service/', role: 'Auth, users, organisations, leave and payroll core domain', tech: ['NestJS', 'JWT', 'MongoDB'], icon: 'lucide:users' },
    { name: 'projects-manager/', role: 'Project and task time duration aggregation', tech: ['NestJS', 'Kafka'], icon: 'lucide:folder-kanban' },
    { name: 'plans/', role: 'Subscription and billing domain', tech: ['NestJS'], icon: 'lucide:credit-card' },
    { name: 'notifications/', role: 'Email and notification processing', tech: ['NestJS', 'Kafka'], icon: 'lucide:bell' },
    { name: 'storage-producer/', role: 'Object upload pipeline for screenshots and artefacts', tech: ['NestJS', 'S3', 'Cloudflare R2'], icon: 'lucide:hard-drive' },
    { name: 'auto-update/', role: 'Desktop release and update distribution server', tech: ['Express'], icon: 'lucide:download' },
    { name: 'trackhrs-front/', role: 'Public marketing site and lead capture', tech: ['Next.js'], icon: 'lucide:globe' },
    { name: 'trackhrs-portal/', role: 'Authenticated operations and admin experience', tech: ['Next.js'], icon: 'lucide:layout-dashboard' },
  ],
  pipelineMini: [
    { step: 1, title: 'Capture', description: 'Desktop agent', icon: 'lucide:monitor' },
    { step: 2, title: 'Ingest', description: 'Kafka + dedup', icon: 'lucide:git-branch' },
    { step: 3, title: 'Classify', description: 'BullMQ + ML API', icon: 'lucide:brain' },
    { step: 4, title: 'Insight', description: 'Cache + dashboards', icon: 'lucide:chart-line' },
  ],
  pipeline: {
    heading: 'The activity intelligence pipeline',
    intro:
      'This is the core of the product. Every step exists to solve a specific failure mode: duplicate events, write amplification, a slow model call blocking ingest, or a stale dashboard. Read top to bottom, it is the journey from one keystroke to one number on a manager’s screen.',
    steps: [
      { step: 1, title: 'Desktop activity event', description: 'Captured by the Tauri agent and sent over a secure API boundary. If the network is down, it buffers locally in SQLite first.', tech: ['Tauri 2', 'Rust', 'SQLite'], icon: 'lucide:monitor' },
      { step: 2, title: 'Kafka topic', description: 'High-throughput ingestion, deliberately decoupled from everything downstream so a slow consumer can never slow down capture.', tech: ['Apache Kafka'], icon: 'lucide:git-branch' },
      { step: 3, title: 'Activity consumer', description: 'Processes the stream with partition-aware scaling, so adding replicas grows throughput with the consumer group.', tech: ['NestJS', 'Consumer groups'], icon: 'lucide:cpu' },
      { step: 4, title: 'Redis dedup', description: 'An O(1) key check makes processing multi-replica-safe, so the same event is never counted twice.', tech: ['Redis'], icon: 'lucide:copy-check' },
      { step: 5, title: 'Batch service', description: 'Collects up to 100 items or a 5-second window before writing, giving up to 100× fewer immediate database writes on the hot path.', tech: ['Batching'], icon: 'lucide:layers' },
      { step: 6, title: 'MongoDB bulk upsert', description: 'A document model that fits evolving activity payloads and organisation structures, paired with indexed reporting queries.', tech: ['MongoDB', 'Replica set'], icon: 'lucide:database' },
      { step: 7, title: 'BullMQ classification queue', description: 'Classification runs as a background job, keeping latency-sensitive writes off the same path as heavier work.', tech: ['BullMQ', 'Redis'], icon: 'lucide:list-checks' },
      { step: 8, title: 'Classifier API', description: 'A bearer-key FastAPI service, so the ML lifecycle and its dependencies iterate independently of the TypeScript services.', tech: ['Python', 'FastAPI'], icon: 'lucide:brain' },
      { step: 9, title: 'Classification update', description: 'Categories are persisted. Failures fall through a circuit breaker, exponential retry and a dead-letter collection that a distributed cron reprocesses.', tech: ['Circuit breaker', 'Retry', 'DLQ'], icon: 'lucide:shield-check' },
      { step: 10, title: 'Cache invalidation', description: 'An invalidation event means the next dashboard read is fresh, without depending on a short TTL to expire.', tech: ['Redis'], icon: 'lucide:refresh-cw' },
    ],
  },
  techDecisions: [
    { area: 'Event streaming', choice: 'Apache Kafka', rationale: 'Decouples ingestion from downstream processing and supports replay-friendly analytics workloads at high throughput.' },
    { area: 'Background work', choice: 'BullMQ', rationale: 'Classification and delayed jobs stay off the hot path, so latency-sensitive writes stay fast.' },
    { area: 'Cache & coordination', choice: 'Redis Cluster', rationale: 'One system covers cache acceleration, deduplication, queue backing and the distributed locks that make cron multi-replica-safe.' },
    { area: 'Persistence', choice: 'MongoDB replica set', rationale: 'Flexible documents suit evolving activity payloads and org structures, and pair naturally with batched upserts.' },
    { area: 'Desktop client', choice: 'Tauri 2 + Rust', rationale: 'Native-level performance and low memory overhead, with the system-level access browser-only approaches cannot reach.' },
    { area: 'ML service', choice: 'Python FastAPI', rationale: 'Keeps model iteration and Python dependencies fully isolated from the strongly typed core platform.' },
  ],
  achievements: [
    { title: 'Production-style distributed platform', description: 'Rust desktop agent, modern web apps and microservices delivered end to end.', icon: 'lucide:boxes' },
    { title: 'Up to 100× fewer immediate DB writes', description: 'Batching on the ingest path substantially reduces write amplification.', icon: 'lucide:trending-down' },
    { title: 'High-throughput async processing', description: 'Kafka and BullMQ absorb traffic spikes and keep pipelines resilient.', icon: 'lucide:zap' },
    { title: 'Multi-replica-safe coordination', description: 'Redis dedup keys and distributed locks keep cron and background work idempotent.', icon: 'lucide:lock' },
    { title: 'Isolated ML service', description: 'A dedicated Python classifier while the core platform stays strongly typed in TypeScript.', icon: 'lucide:brain' },
    { title: 'Full product surface', description: 'Desktop app, admin portal, marketing site, update server and the backend ecosystem behind them.', icon: 'lucide:layout-grid' },
  ],
  scalability: [
    'Microservice-oriented, independently deployable services',
    'Asynchronous pipelines that absorb traffic spikes',
    'Cache-first reads for low-latency dashboards',
    'Explicit deduplication and idempotency controls',
    'Kafka consumer groups for partition-aware horizontal scaling',
    'Distributed locks so cron and reprocessor jobs run exactly once',
    'MongoDB replica set for write and read resilience',
  ],
  security: [
    'JWT authentication and role-aware APIs',
    'bcrypt password hashing, with OTP and reset flows on Redis TTL',
    'API key authentication for classifier calls',
    'Rate limiting and secure headers across Node services',
    'Retry, circuit breaker and DLQ to contain blast radius',
    'Structured /health checks for readiness and liveness',
  ],
  stack: ['NestJS', 'Rust', 'Tauri 2', 'Python', 'FastAPI', 'Apache Kafka', 'Redis', 'BullMQ', 'MongoDB', 'Next.js', 'Docker', 'Kubernetes', 'Jenkins'],
  featured: true,
  order: 1,
  accent: 'primary',
}
